title: My Blog # your site title
author: Chandra Dev Singh
email: info@chandrasingh.com.np # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://amarchandr.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rockeramar # replace with your_twitter_username or comment to remove link from footer
github_username:  amarchandr # replace with your_github_username or comment to remove link from footer
instagram_username: amarchandr # replace with your_instagram_username or comment to remove link from footer
social:
  name: Chandra Dev Singh
  links:
    - https://twitter.com/rockeramar
    - https://www.facebook.com/chandrasingh143
    - https://www.linkedin.com/in/chandrasingh143/
    - https://plus.google.com/+chandrasingh143
    - https://github.com/amarchandr

disqus:
  shortname: amar # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
